---
is_debug: true
listen:
  type: port
  bind_ip: 127.0.0.1
  port: 10000
mongodb:
  host: localhost
  port: 27017
  database: book-library
  auth_db:
  username:
  password:
  collection: books
mysql:
  host: 94.228.124.31
  port: 3306
  database: test
  username: test
  password: test
  net: tcp

